### ISSUE TITLE
[BUG] Random error message every time I start Neovim

### ISSUE THREAD

**Issue by MrKrot792** [gisketch/triforce.nvim#32]
Image:
<img width="995" height="292" alt="Image" src="https://github.com/user-attachments/assets/8a6dd2b6-fbdf-4c34-914b-d595f15a1b71" />

Error:
```
Failed to run `config` for triforce.nvim

...share/nvim/lazy/triforce.nvim/lua/triforce/languages.lua:151: attempt to index a nil value

# stacktrace:
  - /triforce.nvim/lua/triforce/languages.lua:151 _in_ **register_custom_languages**
  - /triforce.nvim/lua/triforce.lua:127 _in_ **setup**
  - ~/.config/nvim/lua/plugins/triforce.lua:11 _in_ **config**
  - ~/.config/nvim/lua/config/lazy.lua:25
  - ~/.config/nvim/init.lua:3
```

not sure if there's a need for more info? if so, request please

**Comment by DrKJeff16** [comment]
@MrKrot792 Thanks for the issue!

Were you passing `nil` to `custom_languages` in setup? Either way I just pushed a commit that should fix this.

If there are still issues please comment below and I'll make sure to check it out.

**Comment by MrKrot792** [comment]
@DrKJeff16 Nope! the issue is still present, even after your commit.

I'm using the default config, and here's my `custom_languages`:
```lua
-- Add custom language support
custom_languages = {
    gleam = { icon = "✨", name = "Gleam" },
    odin = { icon = "🔷", name = "Odin" },
    -- Add more languages...
},
```
